### ISSUE TITLE
Package Installed Issue by npm (laravel 7)

### ISSUE THREAD

**Issue by alamin899** [alimranahmed/LaravelAdminator#5]
when i install package by npm its first time installed package but when i want to install another package by npm it automatically remove previous package

**Comment by alimranahmed** [comment]
@alaminhossen899 
Can you please explain a bit more which package you wanted to install and how you tried to install.

**Comment by alamin899** [comment]
after install laravel adminator when i install npm in my adminator project
its installed successfully but if i want install any pacakage by npm it
auto remove another pacakage which is recently installed but new package
installed.i faced this problem with vue js pacakage by npm . i and one of my team member also face same problem

**Comment by alimranahmed** [comment]
@alaminhossen899 

Thanks for your reply.

I got your point. 
I need exact command you run to install package and what are the output/error your are getting while installing package to find out the root cause. 

Have you tried with updated npm?
Have you tried with **yarn** instead of npm? Yarn seems faster and more flexible but works with same package.json file.
